### ISSUE TITLE
Create the solid.js file

### ISSUE THREAD

**Issue by Jared0211** [Jared0211/IDGS08C-LosPepos#1]
add a new file to define the SOLID code concepts

**Comment by IsaiZAm13** [comment]
Se subio mi parte de solid

**Comment by MarioGzz26** [comment]
Añadí mi parte de solid

**Comment by AbielGomez09** [comment]
Adjunto mi parte de solid

**Comment by Jared0211** [comment]
Doy por cerrado el Isseu

**Comment by Sarita12345678** [comment]
Añado mi parte de solid
